# Generated by Django 5.0.5 on 2024-06-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0002_pinjam_buku'),
    ]

    operations = [
        migrations.RunSQL(
            sql=("ALTER TABLE pinjam_buku ADD COLUMN petugas VARCHAR(255)"),
            reverse_sql=("ALTER TABLE pinjam_buku DROP COLUMN petugas")
        )
    ]
